// color array
var buttonColours = ["red", "blue", "green", "yellow"];
var gamePattern = [];
var userClickedPattern = [];
var started = false;
var level = 0;

function startOver(){
    level = 0;
    started = false;
    gamePattern = [];
}

// event to track a user's keyboard click to start the game
$(document).on("keydown", function(){
    if(started === false){
        started = true;
        setTimeout(nextSequence, 100);
    }
});


// event to track if user has clicked any button on the screen and give response accordingly
$(".btn").click(function () {
    var userChosenColour = $(this).attr("id");

    userClickedPattern.push(userChosenColour);

    playSound(userChosenColour);

    animateButton(userChosenColour);

    checkAnswer(userClickedPattern.length-1);
});


// checking if the user has given correct pattern generated by the game
function checkAnswer(currentLevel) {
    if(gamePattern[currentLevel] === userClickedPattern[currentLevel]){
        if(userClickedPattern.length === gamePattern.length){
            setTimeout(nextSequence , 1000);
        }
    }
    else{
        playSound("Wrong");
        $("body").addClass("game-over");
        setTimeout(function(){
            $("body").removeClass("game-over");
        }, 200);
        $("#level-title").text("Game Over, Press any key to Restart");
        startOver();
    }

}   


// function to generate random next pattern for the user to continue his game
function nextSequence() {

    userClickedPattern = [];

    var randomNo = Math.floor(Math.random() * 4);
    var randomChosenColour = buttonColours[randomNo];

    gamePattern.push(randomChosenColour);
    $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
    playSound(randomChosenColour);

    if (started == true) {
        $("h1").text("Current Level " + level);
        level++;
    }
}

// function to play the required audio
function playSound(chosenColor) {
    var audio = new Audio("sounds/" + chosenColor + ".mp3");
    audio.play();
}


// function to animate the button when the user clicks a button
function animateButton(btn) {
    $("#" + btn).addClass("pressed");
    setTimeout(function () {
        $("#" + btn).removeClass("pressed");
    }, 100);
}